import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {retrieve,validation,intakeValidation,contextComplete,moneyEqual,exceeds,schemaErrors,detectMime,validateCitations} from '../lib/engine.ts';
const read=p=>JSON.parse(fs.readFileSync(new URL('../lib/data/'+p,import.meta.url),'utf8'));
const cards=read('policy_cards.json'),c=read('example_extraction.json'),x=read('example_employee_context.json');
test('new library has 12 current cards and excludes archived card',()=>{assert.equal(cards.filter(p=>p.status==='CURRENT').length,12);assert(cards.some(p=>p.policy_id==='HOTEL-001-2024'&&p.status==='OUTDATED'))});
test('meal retrieval injects deadline and current meal cards',()=>assert.deepEqual(retrieve({...c,category:'meal',currency:'SGD'},x,cards).policy_ids,['GEN-001','MEAL-001','MEAL-002','MEAL-003']));
test('hotel foreign-currency retrieval injects FX evidence',()=>assert.deepEqual(retrieve({...c,category:'hotel',currency:'USD'},x,cards).policy_ids,['GEN-001','HOTEL-001','HOTEL-002','FX-001']));
test('transport retrieval uses only current transport cards',()=>{const ids=retrieve({...c,category:'transport'},x,cards).policy_ids;assert.deepEqual(ids,['GEN-001','TRANSPORT-001','TRANSPORT-002','TRANSPORT-003']);assert(!ids.includes('HOTEL-001-2024'))});
test('airfare retrieval maps to current travel cards',()=>assert.deepEqual(retrieve({...c,category:'airfare'},x,cards).policy_ids,['GEN-001','TRAVEL-001','TRAVEL-002']));
test('280 versus 300 blocks',()=>assert(validation(c,{...x,claimed_amount:300}).some(s=>s.includes('Claimed amount'))));
test('complete intake accepts matching employee and receipt facts',()=>assert.equal(contextComplete(x),true));
test('intake routes an unreadable receipt field to human review',()=>{const unreadable=structuredClone(c);unreadable.amount=null;unreadable.field_confidence.amount=0;assert(intakeValidation(unreadable,x).some(s=>s.includes('Amount')))});
test('0.1+0.2 is not silently accepted as exact 0.3',()=>assert.equal(moneyEqual(.1+.2,.3),false));
test('per-night cap exact and foreign converted',()=>{assert.equal(exceeds(500,1,250,2),false);assert.equal(exceeds(220,1.3,250,1),true)});
test('invalid date blocks retrieval',()=>assert(retrieve({...c,date:'2026-02-30'},x,cards).flags.includes('invalid_or_missing_date')));
test('unknown category blocks retrieval',()=>assert(retrieve({...c,category:'other'},x,cards).flags.includes('unsupported_category')));
test('fake and duplicate citations are rejected',()=>{const ids=cards.filter(p=>p.status==='CURRENT').map(p=>p.policy_id);assert.equal(validateCitations({policy_ids:['ADMIN-999']},ids),false);assert.equal(validateCitations({policy_ids:['GEN-001','GEN-001']},ids),false)});
test('JSON extra field and invalid date rejected',()=>{const errors=schemaErrors({...c,date:'2026-02-30',extra:1},read('extraction.schema.json'));assert(errors.length>=2)});
test('file signatures checked independent of extension',()=>{assert.equal(detectMime(new TextEncoder().encode('hello world')),null);assert.equal(detectMime(new TextEncoder().encode('%PDF-1.7 content')),'application/pdf')});
