import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {retrieve,validation,demoAssess,moneyEqual,exceeds,schemaErrors,detectMime,validateCitations} from '../lib/engine.ts';
const read=p=>JSON.parse(fs.readFileSync(new URL('../lib/data/'+p,import.meta.url),'utf8'));
const cards=read('policy_cards.json'),cases=read('retrieval_cases.json'),c=read('example_extraction.json'),x=read('example_employee_context.json');
for(const r of cases){test(r.case_id+' matches member4 policy IDs/flags',()=>{const a=retrieve(r.claim,r.context,cards);assert.deepEqual(a.policy_ids,r.expected_policy_ids);assert.deepEqual(a.flags,r.expected_flags)});test(r.case_id+' demonstration pre-screen expected state',()=>{const flags=validation(r.claim,r.context);const a=flags.length?'needs_human_review':demoAssess(r.claim,r.context,retrieve(r.claim,r.context,cards)).status;assert.equal(a,r.expected_assessment_status)})}
test('280 versus 300 blocks',()=>assert(validation(c,{...x,claimed_amount:300}).some(s=>s.includes('金额'))));
test('corrected extraction preserves original low confidence',()=>{const orig=structuredClone(c);orig.date=null;orig.field_confidence.date=0;assert(validation(c,x,orig).some(s=>s.includes('置信度')))});
test('0.1+0.2 is not silently accepted as exact 0.3',()=>assert.equal(moneyEqual(.1+.2,.3),false));
test('equal amounts normalize decimal representation',()=>assert(moneyEqual(280,280.00)));
test('per-night cap exact and foreign converted',()=>{assert.equal(exceeds(500,1,250,2),false);assert.equal(exceeds(220,1.3,250,1),true)});
test('invalid date returns review',()=>assert.deepEqual(retrieve({...c,date:'2026-02-30'},x,cards).flags,['invalid_or_missing_date']));
test('unknown category cannot be eligible',()=>assert(retrieve({...c,category:'other'},x,cards).flags.includes('unsupported_category')));
test('policy conflict preserved',()=>assert(retrieve(c,x,[...cards,cards.find(p=>p.policy_id==='HOTEL-001')]).flags.includes('policy_conflict:HOTEL-001')));
test('night transport exception not truncated',()=>{const r=retrieve({...c,category:'transport'},{...x,transport_mode:'taxi',night_travel:true},cards);assert(r.policy_ids.includes('TRANSPORT-003'))});
test('taxi unknown mode requires review',()=>assert(retrieve({...c,category:'transport'},{...x,transport_mode:null},cards).flags.length));
test('missing optional tax does not block core fields',()=>{const d=structuredClone(c);d.tax_amount=null;d.field_confidence.tax_amount=0;assert.equal(validation(d,x).length,0)});
test('unknown evidence cannot become eligible',()=>{const d={...x,claimed_amount:200,manager_approval:'unknown'};assert.equal(demoAssess({...c,amount:200},d,retrieve({...c,amount:200},d,cards)).status,'needs_human_review')});
test('alcohol violation is ineligible with complete evidence',()=>{const r=cases[0];const ctx={...r.context,contains_alcohol:true};assert.equal(demoAssess(r.claim,ctx,retrieve(r.claim,ctx,cards)).status,'likely_ineligible')});
test('unknown meal boolean is human',()=>{const r=cases[0];const ctx={...r.context,contains_alcohol:null};assert.equal(demoAssess(r.claim,ctx,retrieve(r.claim,ctx,cards)).status,'needs_human_review')});
test('fake citation is rejected',()=>assert.equal(validateCitations({policy_ids:['ADMIN-999']},cards.map(p=>p.policy_id)),false));
test('JSON extra field and invalid date rejected',()=>{const errors=schemaErrors({...c,date:'2026-02-30',extra:1},read('extraction.schema.json'));assert(errors.length>=2)});
test('file signatures checked independent of extension',()=>{assert.equal(detectMime(new TextEncoder().encode('hello world')),null);assert.equal(detectMime(new TextEncoder().encode('%PDF-1.7 content')),'application/pdf')});
