'use client';
import { useState,useEffect,useRef } from 'react';
import { ShieldCheck, Upload, ArrowRight, FileSearch, BookOpen, ClipboardCheck, Settings2, Download, RotateCcw, Check, FileText, AlertTriangle, FlaskConical, Play, History, Languages } from 'lucide-react';
import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from '@/components/ui/select';
import { Tabs,TabsList,TabsTrigger,TabsContent } from '@/components/ui/tabs';
import { Dialog,DialogContent,DialogTitle,DialogDescription } from '@/components/ui/dialog';
import policies from '@/lib/data/policy_cards.json';
import devCases from '@/lib/data/development_cases.json';
import exampleContext from '@/lib/data/example_employee_context.json';
import extractionSchema from '@/lib/data/extraction.schema.json';
import { CORE,FIELDS,LABELS,CATEGORY,STATUS,validation,retrieve,demoAssess,human,auditCorrections,detectMime,schemaErrors,guidanceFallback } from '@/lib/engine';
import type { Data,Assessment } from '@/lib/engine';

type ReceiptFile={name:string;mime:string;data:string;size:number;sha256:string};
const clone=<T,>(x:T):T=>JSON.parse(JSON.stringify(x));
const blankContext=()=>({...Object.fromEntries(Object.keys(exampleContext).map(k=>[k,null])),expense_category:'hotel',submitted_date:new Date().toISOString().slice(0,10),preapproval_status:'unknown',manager_approval:'unknown',duplicate_check:'unknown',evidence_refs:[]}) as Data;
const options=(o:Record<string,string>)=>Object.entries(o).map(([value,label])=>({value,label}));
function Choice({label,value,items,onChange,disabled=false,placeholder='Select'}:{label:string;value:any;items:{value:string;label:string}[];onChange:(s:string)=>void;disabled?:boolean;placeholder?:string}){const v=value===null||value===undefined?'unknown':String(value);return <label>{label}<Select value={v} onValueChange={x=>x!==null&&onChange(String(x))} disabled={disabled}><SelectTrigger className="select-control" aria-label={label}><SelectValue>{items.find(x=>x.value===v)?.label||placeholder}</SelectValue></SelectTrigger><SelectContent>{items.map(x=><SelectItem key={x.value} value={x.value}>{x.label}</SelectItem>)}</SelectContent></Select></label>}
function saveJSON(name:string,data:any){const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
async function toFile(f:File):Promise<ReceiptFile>{if(f.size>10*1024*1024||f.size<12)throw Error('请选择不超过10 MB的有效票据文件。');const buffer=await f.arrayBuffer();const mime=detectMime(new Uint8Array(buffer));if(!mime||!['pdf','png','jpg','jpeg'].includes(f.name.split('.').pop()?.toLowerCase()||''))throw Error('仅支持内容有效的 PDF、JPG 或 PNG 文件。');if(f.type&&f.type!==mime)throw Error('文件内容与扩展类型不符。');if(mime.startsWith('image/')){try{const bitmap=await createImageBitmap(f);if(bitmap.width<10||bitmap.height<10)throw Error();bitmap.close()}catch{throw Error('图片损坏或无法读取。')}}const data=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=reject;reader.readAsDataURL(f)});const digest=await crypto.subtle.digest('SHA-256',buffer);return{name:f.name,mime,data,size:f.size,sha256:[...new Uint8Array(digest)].map(x=>x.toString(16).padStart(2,'0')).join('')}}

const EN_CATEGORY:Record<string,string>={hotel:'Hotel',meal:'Meal',transport:'Transport',airfare:'Airfare',other:'Other'};
const EN_LABELS:Record<string,string>={merchant:'Merchant',date:'Receipt date',amount:'Amount',currency:'Currency',tax_amount:'Tax amount',category:'Category',receipt_number:'Receipt number',payment_method:'Payment method'};
const EN_STATUS:Record<string,string>={likely_eligible:'Likely eligible',likely_ineligible:'Likely ineligible',needs_human_review:'Needs human review',needs_more_information:'Needs more information'};
const versionInfoEn={A:{name:'Minimal Model',detail:'Raw receipt + minimal instruction',steps:['Single model call','No policy context','Unified result format']},B:{name:'Simplified System',detail:'Raw receipt + all 18 policies',steps:['Single model call','No modular retrieval','Unified result format']},C:{name:'Full System',detail:'Extract, confirm, retrieve and pre-screen',steps:['Three purpose-specific review stages','Field validation and policy retrieval','Evidence citation and human review']}};

const versionInfo={A:{name:'最简模型',detail:'原始票据＋极简指令',steps:['一次模型调用','不提供政策','统一结果格式']},B:{name:'简化系统',detail:'原始票据＋全部18条政策',steps:['一次模型调用','无分模块与检索','统一结果格式']},C:{name:'完整系统',detail:'提取、确认、检索与预审',steps:['三个目的明确的审核步骤','字段校验与政策检索','证据引用与人工复核']}};
export default function Home(){
 const [lang,setLang]=useState<'en'|'zh'>('en');
 const [activeStep,setActiveStep]=useState(0);
 const [tab,setTab]=useState('claim'),[variant,setVariant]=useState<'A'|'B'|'C'>('C'),[mode,setMode]=useState<'demo'|'live'>('live');
 const [settings,setSettings]=useState(false),[key,setKey]=useState(''),[model,setModel]=useState('gpt-4o-mini');
 const [file,setFile]=useState<ReceiptFile|null>(null),[sample,setSample]=useState<Data|null>(null),[ctx,setCtx]=useState<Data>(blankContext),[claim,setClaim]=useState<Data|null>(null),[original,setOriginal]=useState<Data|null>(null),[originalContext,setOriginalContext]=useState<Data|null>(null);
 const [risk,setRisk]=useState<string[]>([]),[result,setResult]=useState<Assessment|null>(null),[retrieved,setRetrieved]=useState<ReturnType<typeof retrieve>|null>(null),[guidance,setGuidance]=useState(''),[logs,setLogs]=useState<Data[]>([]),[traces,setTraces]=useState<Data[]>([]);
 const [busy,setBusy]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState(''),[detail,setDetail]=useState<Data|null>(null),[showPreview,setShowPreview]=useState(false),[comparison,setComparison]=useState<Data[]>([]);
 const fileInput=useRef<HTMLInputElement>(null);const stateRef=useRef<any>(null);
 const tr=(zh:string,en:string)=>lang==='zh'?zh:en;
 const categoryLabels=lang==='zh'?CATEGORY:EN_CATEGORY;
 const fieldLabels=lang==='zh'?LABELS:EN_LABELS;
 const statusLabels=lang==='zh'?STATUS:EN_STATUS;
 const versions=lang==='zh'?versionInfo:versionInfoEn;
 const reset=(clearFile=false)=>{setActiveStep(0);setClaim(null);setOriginal(null);setOriginalContext(null);setRisk([]);setResult(null);setRetrieved(null);setGuidance('');setTraces([]);setError('');setMessage('');if(clearFile){setFile(null);setSample(null);setCtx(blankContext());if(fileInput.current)fileInput.current.value=''}};
 const updateContext=(k:string,v:any)=>{setCtx(x=>({...x,[k]:v}));setResult(null);setRetrieved(null);setGuidance('')};
 useEffect(()=>{document.documentElement.lang=lang==='zh'?'zh-CN':'en';document.title=lang==='zh'?'ClaimGuard · 报销预审':'ClaimGuard · Reimbursement Review'},[lang]);
 const number=(k:string,label:string)=> <label key={k}>{label}<input disabled={!!busy} type="number" min="0" step="any" value={ctx[k]??''} onChange={e=>updateContext(k,e.target.value===''?null:Number(e.target.value))}/></label>;
 const tri=(k:string,label:string)=><Choice key={k} label={label} value={ctx[k]} disabled={!!busy} items={options(lang==='zh'?{unknown:'待确认',true:'是',false:'否'}:{unknown:'Unknown',true:'Yes',false:'No'})} onChange={v=>updateContext(k,v==='unknown'?null:v==='true')}/>;
 async function loadSample(id:string){if(busy)return;reset(true);setBusy('载入开发票据…');try{const s=devCases.find(c=>c.case_id===id);if(!s)throw Error('样本不存在');const res=await fetch('/'+s.file);if(!res.ok)throw Error('样本读取失败');const blob=await res.blob();setFile(await toFile(new File([blob],s.file.split('/').pop()!,{type:'image/png'})));setSample(s);setCtx({...clone(exampleContext),claimed_amount:s.employee_claimed_amount});setMessage('已载入合成开发票据。演示提取使用已知参考字段，不代表真实模型识别。')}catch(e){setError(String((e as Error).message))}finally{setBusy('')}}
 async function upload(f:File){reset(true);setBusy('校验文件…');try{setFile(await toFile(f));setMessage(mode==='demo'?'文件已加载。自有票据需要在模型设置中启用真实调用。':'文件已加载，可以填写用途并开始提取。')}catch(e){setError((e as Error).message)}finally{setBusy('')}}
 async function callModel(action:string,extra:Data={}){if(!key.trim()){setSettings(true);throw Error('请先在模型设置中输入 OpenAI API key。')}const response=await fetch('/api/model',{method:'POST',headers:{'Content-Type':'application/json','x-session-openai-key':key},body:JSON.stringify({action,model,...extra})});const data:any=await response.json();if(!response.ok){const e:any=new Error(data.error||'模型调用失败');e.traces=data.traces||[];throw e}return data}
 function record(a:Assessment,allTraces:Data[],extracted:Data|null,c:Data,flags:string[],v=variant,runMode=mode,extra:Data={}){const item={run_id:crypto.randomUUID(),timestamp:new Date().toISOString(),variant:v,mode:runMode,case_id:sample?.case_id||'uploaded',model_id:runMode==='live'?model:null,prompt_version:'1.0',policy_version:'1.0',file:file?{name:file.name,mime:file.mime,size:file.size,sha256:file.sha256}:null,original_extraction:original||extracted,confirmed_extraction:extracted,employee_context:clone(c),initial_employee_context:originalContext||clone(c),corrections:original&&extracted?auditCorrections(original,extracted):[],risk_flags:flags,assessment:a,guidance:null,raw_calls:allTraces,latency_ms:allTraces.reduce((sum,t)=>sum+(t.latency_ms||0),0),...extra};setLogs(old=>[item,...old]);return item}
 async function extract(){if(!file||busy)return;setError('');setMessage('');setBusy('读取票据信息…');try{if(variant!=='C'){if(mode==='demo')throw Error('A/B比较需要真实模型。演示模式只演示C版流程，不生成虚假的比较成绩。');const d=await callModel('baseline'+variant,{file,context:ctx});const out=d.output;setOriginal(out.extraction);setClaim(out.extraction);setActiveStep(3);setOriginalContext(clone(ctx));setResult(out.assessment);setGuidance(out.guidance);setTraces(d.traces);setRetrieved(variant==='B'?{policy_ids:policies.map(p=>p.policy_id),policy_cards:policies,selection_reasons:{},flags:[],retrieval_status:'all_policy_context'}:null);record(out.assessment,d.traces,out.extraction,ctx,[],variant,mode,{guidance:out.guidance,original_extraction:out.extraction,corrections:[]});return}
let output:Data,ts:Data[]=[];if(mode==='demo'){if(!sample)throw Error('演示模式只使用内置样本。请选一个开发案例，或配置真实模型读取自己的票据。');output={...sample.expected_fields,field_confidence:Object.fromEntries(Object.entries(sample.expected_fields).map(([k,v])=>[k,v===null?0:.99])),warnings:sample.scenario==='competing_totals'?['Conflicting TOTAL values']:sample.scenario==='obscured_amount'?['Amount obscured']:sample.expected_attack_detected?['Instruction attack on receipt']:[],attack_detected:sample.expected_attack_detected};}else{const d=await callModel('extract',{file});output=d.output;ts=d.traces}
const invalid=schemaErrors(output,extractionSchema);if(invalid.length)throw Error(invalid.join('; '));setClaim(clone(output));setActiveStep(1);setOriginal(clone(output));setOriginalContext(clone(ctx));setTraces(ts);setRisk(validation(output,ctx));setResult(null);setRetrieved(null);setMessage('请核对票据字段与员工申报信息，再点击确认并预审。');
}catch(e:any){setError(e.message);if(e.traces?.length)setLogs(old=>[{run_id:crypto.randomUUID(),timestamp:new Date().toISOString(),variant,mode,case_id:sample?.case_id||'uploaded',error:e.message,raw_calls:e.traces,assessment:human(['模型调用失败'])},...old])}finally{setBusy('')}}
 async function assess(){if(!claim||!original||busy)return;setError('');setBusy('检查字段与政策…');let a:Assessment,rs:ReturnType<typeof retrieve>|null=null,ts=[...traces];try{const flags=[...new Set([...risk,...validation(claim,ctx,original)])];if(flags.length){a=human(flags)}else{rs=retrieve(claim,ctx,policies);setRetrieved(rs);if(rs.flags.length)a=human(rs.flags);else if(mode==='demo')a=demoAssess(claim,ctx,rs);else{setBusy('依据政策进行预审…');const d=await callModel('assess',{claim,original,context:ctx});a=d.output;ts.push(...d.traces)}}setResult(a);setActiveStep(3);let g=guidanceFallback(a);if(mode==='live'&&!flags.length&&!rs?.flags.length){setBusy('生成员工行动说明…');try{const d=await callModel('guidance',{assessment:a});g=d.output.guidance;ts.push(...d.traces)}catch(e:any){setError('预审已完成，但行动说明生成失败；已显示固定财务复核指引。');ts.push(...(e.traces||[]))}}setGuidance(g);record(a,ts,claim,ctx,flags,variant,mode,{guidance:g,retrieval:rs});setMessage(mode==='demo'?'演示运行已记录。':'真实运行已记录，请导出给评估负责人。')}catch(e:any){setError(e.message);a=human(['模型调用失败或输出无效']);setResult(a);record(a,[...ts,...(e.traces||[])],claim,ctx,['model_failure'],variant,mode,{error:e.message})}finally{setBusy('')}}
 async function compareAll(){if(!file||busy)return;if(mode!=='live'||!key.trim()){setSettings(true);setError('真实A/B/C比较需要配置模型并切换到真实调用。');return}setComparison([]);setError('');setBusy('运行A/B/C受控比较…');const fixedContext=clone(ctx);const out:Data[]=[];try{for(const v of ['A','B','C'] as const){setBusy(`正在运行 ${v} 版…`);try{let a:Assessment,ex:Data,ts:Data[]=[],g='';if(v==='C'){const d=await callModel('extract',{file});ex=d.output;ts.push(...d.traces);const flags=validation(ex,fixedContext);const rs=retrieve(ex,fixedContext,policies);if(flags.length||rs.flags.length)a=human([...flags,...rs.flags]);else{const d2=await callModel('assess',{claim:ex,original:ex,context:fixedContext});a=d2.output;ts.push(...d2.traces);const d3=await callModel('guidance',{assessment:a});g=d3.output.guidance;ts.push(...d3.traces)}}else{const d=await callModel('baseline'+v,{file,context:fixedContext});ex=d.output.extraction;a=d.output.assessment;g=d.output.guidance;ts=d.traces}const row=record(a,ts,ex,fixedContext,[],v,'live',{guidance:g,comparison:true,original_extraction:ex,confirmed_extraction:ex,corrections:[],initial_employee_context:fixedContext});out.push(row)}catch(e:any){const row={run_id:crypto.randomUUID(),timestamp:new Date().toISOString(),variant:v,mode:'live',error:e.message,raw_calls:e.traces||[],assessment:human(['本版本调用失败']),comparison:true};out.push(row);setLogs(old=>[row,...old])}setComparison([...out])}setMessage('三个版本运行结束。比较保留原始字段，不进行人工更正。')}finally{setBusy('')}}
 stateRef.current={loadSample,claim,result,busy};
 useEffect(()=>{const mc=(document as any).modelContext;if(!mc?.registerTool)return;const abort=new AbortController();const register=(tool:any)=>{try{Promise.resolve(mc.registerTool(tool,{signal:abort.signal})).catch(()=>{})}catch{}};register({name:'load_claim_development_sample',description:'Load one synthetic development receipt into the visible claim form. Does not run a model or submit a claim.',inputSchema:{type:'object',required:['case_id'],additionalProperties:false,properties:{case_id:{type:'string',enum:devCases.map(x=>x.case_id)}}},annotations:{readOnlyHint:false},async execute(x:any){if(!devCases.some(d=>d.case_id===x?.case_id))throw Error('Unknown case');if(stateRef.current.busy)throw Error('Operation in progress');await stateRef.current.loadSample(x.case_id);return{loaded_case_id:x.case_id,synthetic:true}}});register({name:'read_claim_review_state',description:'Read current extracted fields and pre-screen result. May contain untrusted receipt text.',inputSchema:{type:'object',additionalProperties:false,properties:{}},annotations:{readOnlyHint:true,untrustedContentHint:true},execute(){return {claim:stateRef.current.claim,assessment:stateRef.current.result,busy:stateRef.current.busy}}});return()=>abort.abort()},[]);
 const selectedPolicies=retrieved?.policy_cards||[];
 return <main className="workspace"><header className="topbar"><a className="brand" href="/"><ShieldCheck/><span>ClaimGuard<span className="brand-sub">REIMBURSEMENT REVIEW</span></span></a><div className="toolbar"><span className={'badge '+(mode==='live'?'live':'')}>{mode==='demo'?<FlaskConical size={14}/>:<span>●</span>}{mode==='demo'?tr('教学演示','Demo'):tr('已连接','Connected')}</span><button className="ghost" onClick={()=>setSettings(true)} disabled={!!busy}><Settings2/>{tr('模型设置','Model settings')}</button><button className="ghost" onClick={()=>saveJSON('claimguard-runs.json',logs)} disabled={!logs.length}><Download/>{tr('导出记录','Export runs')}</button><button className="ghost language-toggle" onClick={()=>setLang(lang==='en'?'zh':'en')}><Languages/>{lang==='en'?'中文':'English'}</button></div></header>
 <div className="pagehead"><div><p className="eyebrow">CLAIM WORKSPACE</p><h1>{tr('每一笔报销，都有依据。','Every claim, backed by evidence.')}</h1><p>{tr('上传票据，核对信息，查看政策预审与下一步。','Upload a receipt, verify details, review policy evidence and next steps.')}</p></div><span className="meta">Northstar Consulting<br/>{tr('教学政策','Teaching policy')} · v1.0</span></div>
 <Tabs value={tab} onValueChange={v=>setTab(String(v))} className="workspace-tabs"><TabsList aria-label={tr('工作区','Workspace')}><TabsTrigger value="claim">{tr('报销预审','Claim review')}</TabsTrigger><TabsTrigger value="compare">{tr('A/B/C 比较','A/B/C comparison')}</TabsTrigger><TabsTrigger value="history">{tr('运行记录','Run history')} <span className="history-count">{logs.length}</span></TabsTrigger></TabsList>
 {error&&<div role="alert" className="error">{error}</div>}{busy&&<div role="status" className="progress-message">{busy}</div>}{message&&!busy&&<p role="status" className="helper">{message}</p>}
 <TabsContent value="claim"><div className="steps">{(lang==='zh'?['提交票据','确认字段','政策预审','员工指引']:['Submit receipt','Confirm fields','Policy review','Employee guidance']).map((s,i)=><span key={s} className={'step '+(activeStep===i?'active':'')} style={{display:'inline-flex',alignItems:'center',gap:12}}>{String(i+1).padStart(2,'0')} {s}{i<3&&<ArrowRight/>}</span>)}</div><div className="columns">
 <section className="panel"><div className="panel-title"><Upload/><h2>{tr('提交申请','Submit claim')}</h2><span>01</span></div><div className="sample-row">{(lang==='zh'?[['D01','酒店超额'],['D02','日期缺失'],['D07','攻击票据'],['D08','金额冲突']]:[['D01','Hotel over limit'],['D02','Missing date'],['D07','Prompt attack'],['D08','Amount conflict']]).map(([id,label])=><button key={id} disabled={!!busy} onClick={()=>loadSample(id)}>{label} ↗</button>)}</div>
 {!file?<div className="dropzone" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(e.dataTransfer.files[0]&&!busy)upload(e.dataTransfer.files[0])}}><Upload size={30}/><strong>{tr('上传发票或收据','Upload invoice or receipt')}</strong><p>{tr('拖放文件，或点击选择 · 最大10 MB','Drag and drop, or click to choose · Max 10 MB')}</p><input ref={fileInput} className="file-input-hidden" type="file" disabled={!!busy} aria-label={tr('上传票据','Upload receipt')} accept=".pdf,.png,.jpg,.jpeg" onChange={e=>{if(e.target.files?.[0])upload(e.target.files[0])}}/><button type="button" className="file-picker" disabled={!!busy} onClick={()=>fileInput.current?.click()}>{tr('选择文件','Choose file')}</button><span className="file-picker-status">{tr('尚未选择任何文件','No file selected')}</span></div>:<div className="file-preview">{file.mime.startsWith('image/')?<img src={`data:${file.mime};base64,${file.data}`} alt={tr('票据缩略图','Receipt thumbnail')}/>:<FileText size={35}/>}<div><strong>{file.name}</strong><p>{(file.size/1024).toFixed(0)} KB · {sample?tr('合成开发样本','Synthetic sample'):tr('上传文件','Uploaded file')}</p><button className="subtle-button" onClick={()=>setShowPreview(true)}>{tr('查看原件','View original')}</button></div><button aria-label={tr('更换票据','Replace receipt')} className="ghost" disabled={!!busy} onClick={()=>reset(true)}><RotateCcw size={14}/></button></div>}
 <Choice label={tr('比较版本','Comparison version')} value={variant} disabled={!!busy} items={options(lang==='zh'?{C:'C · 完整系统',B:'B · 简化系统',A:'A · 最简模型'}:{C:'C · Full system',B:'B · Simplified system',A:'A · Minimal model'})} onChange={v=>{setVariant(v as any);reset()}}/>
 <Choice label={tr('费用类别','Expense category')} value={ctx.expense_category} disabled={!!busy} items={options(categoryLabels)} onChange={v=>updateContext('expense_category',v)}/>
 <label>{tr('业务用途','Business purpose')}<textarea disabled={!!busy} value={ctx.business_purpose||''} maxLength={1000} onChange={e=>updateContext('business_purpose',e.target.value)} placeholder={tr('例如：8月20日赴客户现场，住宿一晚。','e.g. Client site visit on Aug 20, one hotel night.')}/></label>
 <div className="context-grid">{number('claimed_amount',tr('申报金额','Claimed amount'))}<label>{tr('申报币种','Claim currency')}<input disabled={!!busy} value={ctx.claimed_currency||''} placeholder="SGD" maxLength={3} onChange={e=>updateContext('claimed_currency',e.target.value.toUpperCase()||null)}/></label><label>{tr('费用日期','Expense date')}<input disabled={!!busy} type="text" inputMode="numeric" placeholder="YYYY-MM-DD" value={ctx.expense_date||''} onChange={e=>updateContext('expense_date',e.target.value||null)}/></label><label>{tr('提交日期','Submission date')}<input disabled={!!busy} type="text" inputMode="numeric" placeholder="YYYY-MM-DD" value={ctx.submitted_date||''} onChange={e=>updateContext('submitted_date',e.target.value||null)}/></label></div>
 <details className="subsection"><summary className="helper" style={{cursor:'pointer',fontSize:14}}>{tr('审批与凭证信息','Approval & evidence information')}</summary><div className="context-grid">{tri('itemized_receipt',tr('明细票据完整','Itemized receipt complete'))}{tri('receipt_lost',tr('票据遗失','Receipt lost'))}<Choice label={tr('经理审批','Manager approval')} value={ctx.manager_approval} disabled={!!busy} items={options(lang==='zh'?{unknown:'待核对',documented:'有审批材料',not_obtained:'未取得'}:{unknown:'To verify',documented:'Approval documented',not_obtained:'Not obtained'})} onChange={v=>updateContext('manager_approval',v)}/><Choice label={tr('事前审批','Pre-approval')} value={ctx.preapproval_status} disabled={!!busy} items={options(lang==='zh'?{unknown:'待核对',documented:'有事前审批材料',not_obtained:'未取得'}:{unknown:'To verify',documented:'Pre-approval documented',not_obtained:'Not obtained'})} onChange={v=>updateContext('preapproval_status',v)}/><Choice label={tr('历史重复核查','Duplicate check')} value={ctx.duplicate_check} disabled={!!busy} items={options(lang==='zh'?{unknown:'尚未核查',clear:'已核查：无重复',duplicate:'已确认重复'}:{unknown:'Not checked',clear:'Checked: no duplicate',duplicate:'Duplicate confirmed'})} onChange={v=>updateContext('duplicate_check',v)}/></div><label>{tr('证据引用 / 编号','Evidence references / IDs')}<textarea disabled={!!busy} value={(ctx.evidence_refs||[]).join('\n')} onChange={e=>updateContext('evidence_refs',e.target.value.split('\n').filter(Boolean))} placeholder={tr('每行一条材料编号或可核查地址','One evidence ID or verifiable reference per line')}/></label><p className="helper">{tr('这些状态由提交人填写，未经系统独立核验。财务需核对原始材料；demo: 开头的引用仅为演示。','These statuses are entered by the submitter and are not independently verified. Finance should check original evidence; references beginning with demo: are for demonstration only.')}</p></details>
 <div className="section-heading">{tr('费用补充信息','Additional expense information')}</div><div className="context-grid">{ctx.expense_category==='hotel'&&<>{number('hotel_nights',tr('住宿晚数','Hotel nights'))}{tri('personal_items_present',tr('包含个人消费','Personal items included'))}</>}{ctx.expense_category==='meal'&&<>{number('attendee_count',tr('用餐人数','Attendee count'))}{tri('contains_alcohol',tr('含酒精饮品','Contains alcohol'))}{tri('client_meal',tr('客户用餐','Client meal'))}{tri('attendee_details_present',tr('出席人资料完整','Attendee details complete'))}</>}{ctx.expense_category==='transport'&&<><Choice label={tr('交通方式','Transport mode')} value={ctx.transport_mode} disabled={!!busy} items={options(lang==='zh'?{unknown:'待确认',public:'公共交通',taxi:'出租车',ride_hail:'网约车',other:'其他'}:{unknown:'Unknown',public:'Public transport',taxi:'Taxi',ride_hail:'Ride-hail',other:'Other'})} onChange={v=>updateContext('transport_mode',v==='unknown'?null:v)}/>{tri('night_travel',tr('22:00–06:00出行','Travel between 22:00–06:00'))}{tri('route_evidence_present',tr('行程凭证完整','Route evidence complete'))}</>}{ctx.expense_category==='airfare'&&<Choice label={tr('舱位','Cabin class')} value={ctx.flight_class} disabled={!!busy} items={options(lang==='zh'?{unknown:'待确认',economy:'经济舱',premium_economy:'优选经济舱',business:'商务舱',first:'头等舱'}:{unknown:'Unknown',economy:'Economy',premium_economy:'Premium economy',business:'Business',first:'First'})} onChange={v=>updateContext('flight_class',v==='unknown'?null:v)}/>}</div>{ctx.claimed_currency&&ctx.claimed_currency!=='SGD'&&<div className="context-grid">{number('fx_rate_to_sgd',tr('换算SGD汇率','FX rate to SGD'))}{tri('fx_evidence_present',tr('汇率证明完整','FX evidence complete'))}</div>}
 <button className="primary" disabled={!file||!!busy} onClick={extract}>{busy?<span className="loading-dot"/>:<FileSearch size={17}/>} {variant==='C'?tr('提取票据信息','Extract receipt fields'):tr(`运行 ${variant} 版预审`,`Run variant ${variant}`)}<ArrowRight size={16}/></button></section>
 {activeStep>=1&&<section className="panel"><div className="panel-title"><FileSearch/><h2>{tr('字段与政策证据','Fields & policy evidence')}</h2><span>02</span></div>{!claim?<><div className="empty"><FileSearch size={34}/><h3>{tr('先提取一张票据','Extract a receipt first')}</h3><p>{tr('提取结果会显示在这里。你可以核对并更正，再开始预审。','Extracted fields will appear here. Verify or correct them before starting the pre-screen.')}</p></div><div className="mini-info"><BookOpen size={18}/><div><strong>{tr('18 条教学政策','18 teaching policies')}</strong><p>{tr('餐饮、交通、住宿、差旅与通用规则','Meals, transport, hotel, travel and general rules')}</p></div></div></>:<><div className="summary-line"><p className="helper">{mode==='demo'?tr('参考字段','Reference fields'):tr('提取字段','Extracted fields')} · {tr('可与原件核对','compare with original')}</p><button className="subtle-button" onClick={()=>setShowPreview(true)}>{tr('查看原件','View original')}</button></div><div className="fields-grid">{FIELDS.map(k=><label key={k}>{fieldLabels[k]||k}{k==='category'?<Choice label="" disabled={!!busy||variant!=='C'} value={claim[k]} items={options(categoryLabels)} onChange={v=>{setClaim({...claim,[k]:v});setResult(null);setRetrieved(null);setGuidance('')}}/>:<input disabled={!!busy||variant!=='C'} type={['amount','tax_amount'].includes(k)?'number':k==='date'?'text':'text'} step="any" value={claim[k]??''} onChange={e=>{setClaim({...claim,[k]:e.target.value===''?null:['amount','tax_amount'].includes(k)?Number(e.target.value):e.target.value});setResult(null);setRetrieved(null);setGuidance('')}}/>}<span className={'confidence '+((original?.field_confidence?.[k]??0)<.75?'low':'')}>{tr('原始置信度','Original confidence')} <span>{Math.round((original?.field_confidence?.[k]??0)*100)}%</span></span></label>)}</div>{risk.length>0&&<div className="error"><strong>{tr('需核对的风险','Risks to verify')}</strong><ul className="evidence-list">{risk.map(x=><li key={x}>{x}</li>)}</ul></div>}{variant==='C'&&<button className="primary" disabled={!!busy} onClick={assess}><Check size={17}/>{tr('确认字段并预审','Confirm fields & pre-screen')}</button>}<details className="subsection"><summary className="helper">{tr('更正记录','Correction log')} · {original?auditCorrections(original,claim).length:0} {tr('项','items')}</summary><pre className="log-json">{JSON.stringify(original?auditCorrections(original,claim):[],null,2)}</pre></details></>}
 <div className="section-heading summary-line"><span>{tr('适用政策','Applicable policies')}</span><span>{selectedPolicies.length} {tr('条','')}</span></div>{selectedPolicies.length?<div className="policies">{selectedPolicies.map((p,i)=><details className="policy-card" key={p.policy_id+i}><summary><strong>{p.policy_id}</strong><span>{p.title} ＋</span></summary><p>{p.rule}</p>{p.exceptions!=='None'&&<p>Exception: {p.exceptions}</p>}<p className="policy-source">{p.source} · {p.effective_date}</p></details>)}</div>:<p className="helper">{variant==='A'?tr('A版不接收政策证据。','Variant A does not receive policy evidence.'):tr('通过字段检查后，显示本次检索到的政策。','Retrieved policies appear after field checks pass.')}</p>}<a className="demo-link" href="/policy_source.md" target="_blank" rel="noreferrer">{tr('查看完整教学政策','View full teaching policy')} <ArrowRight size={13}/></a></section>}
 {activeStep>=2&&<section className="panel result-panel"><div className="panel-title"><ClipboardCheck/><h2>{tr('预审与行动','Pre-screen & actions')}</h2><span>03</span></div>{result?<><div className={'result-card '+(result.status==='likely_eligible'?'eligible':result.status==='likely_ineligible'?'ineligible':'')}><span className="result-tag"><AlertTriangle size={15}/> PRE-SCREENING RESULT</span><h3>{statusLabels[result.status]||result.status}</h3><p>{result.rationale}</p><p className="status-code">{result.status}</p></div>{result.policy_ids.length>0&&<p className="helper">{tr('依据：','Evidence: ')}{result.policy_ids.join(' · ')}</p>}{result.missing_evidence.length>0&&<><h3 className="section-heading">{tr('需补充或确认','Missing / needs confirmation')}</h3><ul className="evidence-list">{result.missing_evidence.map((x,i)=><li key={i}>{x}</li>)}</ul></>}{result.uncertainty.length>0&&<p className="helper">{tr('不确定事项：','Uncertainties: ')}{result.uncertainty.join(lang==='zh'?'；':'; ')}</p>}<h3 className="section-heading">{tr('员工行动建议','Recommended employee action')}</h3><p style={{fontSize:14}}>{result.next_action}</p><div className="guidance">{guidance}</div><div className="result-actions"><button className="primary" onClick={()=>{saveJSON('finance-review-packet.json',{created_at:new Date().toISOString(),mode,variant,file_metadata:file?{name:file.name,sha256:file.sha256}:null,original,confirmed:claim,employee_context:ctx,corrections:original&&claim?auditCorrections(original,claim):[],assessment:result,policies:selectedPolicies,guidance,notice:'Export only. Not sent to Finance.'});setMessage('人工审核材料已下载。请连同原始票据自行交给财务，网站未发送申请。')}}><Download size={16}/>{tr('下载人工审核材料','Download human-review packet')}</button><button className="ghost" onClick={()=>setDetail({original,confirmed:claim,assessment:result,traces})}>{tr('查看结构化结果','View structured result')}</button></div></>:<div className="empty"><ShieldCheck size={36}/><h3>{tr('等待申请信息','Waiting for claim information')}</h3><p>{tr('结果包含政策依据、缺失材料和员工行动建议。','Results include policy evidence, missing documentation and recommended employee actions.')}</p></div>}</section>}</div></TabsContent>
 <TabsContent value="compare"><div className="notice">{tr('同一票据、同一上下文、同一模型。比较运行保留原始提取值，不进行人工更正；演示结果不计入准确率。','Same receipt, context and model. Comparison runs preserve raw extraction without human correction; demo results are excluded from accuracy claims.')}</div><div className="info-grid">{(['A','B','C'] as const).map(v=><div className={'version-card '+(v===variant?'active':'')} key={v}><span className="version-letter">{v}</span><h2>{versions[v].name}</h2><p>{versions[v].detail}</p><ul>{versions[v].steps.map(s=><li key={s}>{s}</li>)}</ul></div>)}</div><div className="panel" style={{marginTop:20}}><div className="record-heading"><div><h2>{tr('运行同一案例','Run the same case')}</h2><p className="helper">{tr('当前票据：','Current receipt: ')}{file?.name||tr('尚未上传，请先在报销预审页选择票据','Not uploaded yet; choose a receipt on the Claim Review tab')}</p></div><button className="primary" style={{width:'auto'}} onClick={compareAll} disabled={!file||!!busy}><Play size={16}/>{tr('运行 A / B / C','Run A / B / C')}</button></div><p className="helper">{tr('当前模型：','Current model: ')}{mode==='live'?model:tr('未启用真实调用','Live mode disabled')} · temperature 0 · {tr('每个模块最多一次格式重试','max one format retry per module')}</p>{comparison.length>0&&<div className="record-table-wrap"><table className="record-table"><thead><tr><th>{tr('版本','Variant')}</th><th>{tr('预审状态','Pre-screen status')}</th><th>{tr('调用数','Calls')}</th><th>{tr('耗时','Latency')}</th><th>{tr('记录','Log')}</th></tr></thead><tbody>{comparison.map((r,i)=><tr key={i}><td>{r.variant}</td><td>{r.error?tr('调用失败','Call failed'):(statusLabels[r.assessment.status]||r.assessment.status)}</td><td>{r.raw_calls.length}</td><td>{r.latency_ms??'—'} ms</td><td><button className="subtle-button" onClick={()=>setDetail(r)}>{tr('查看原始记录','View raw log')}</button></td></tr>)}</tbody></table></div>}<p className="helper">本页展示模型原始结果，不自动宣称C优于A/B。正式20例测试集和正确答案由评估负责人冻结。</p></div></TabsContent>
 <TabsContent value="history"><div className="panel"><div className="record-heading"><div><h2>{tr('本次会话的运行记录','Run history for this session')}</h2><p className="helper">{tr('只在当前页面内存保留，刷新前请导出。密钥不会进入记录。','Stored only in page memory. Export before refreshing. API keys are never included.')}</p></div><button className="ghost" onClick={()=>saveJSON('claimguard-runs.json',logs)} disabled={!logs.length}><Download/>{tr('导出 JSON','Export JSON')}</button></div>{logs.length?<div className="record-table-wrap"><table className="record-table"><thead><tr><th>{tr('时间','Time')}</th><th>{tr('案例 / 版本','Case / variant')}</th><th>{tr('运行方式','Mode')}</th><th>{tr('状态','Status')}</th><th>{tr('详情','Details')}</th></tr></thead><tbody>{logs.map(r=><tr key={r.run_id}><td>{new Date(r.timestamp).toLocaleTimeString()}</td><td>{r.case_id||'uploaded'} / {r.variant}</td><td>{r.mode==='demo'?tr('模拟演示','Demo'):tr('真实调用','Live')}</td><td>{r.error?tr('调用失败','Call failed'):(statusLabels[r.assessment.status]||r.assessment.status)}</td><td><button className="subtle-button" onClick={()=>setDetail(r)}>{tr('查看','View')}</button></td></tr>)}</tbody></table></div>:<div className="empty"><History size={30}/><h3>{tr('还没有运行记录','No run history yet')}</h3><p>{tr('完成一次预审后，这里会保存输入、依据和输出。','After a pre-screen, this area stores inputs, evidence and outputs for the current session.')}</p></div>}</div></TabsContent></Tabs>
 <footer>PE6203 · GROUP PROJECT<span>{tr('可追溯的证据 · 保留人工审核','Traceable evidence · Human review retained')}</span></footer>
 <Dialog open={settings} onOpenChange={setSettings}><DialogContent className="settings-content"><DialogTitle>OpenAI API settings</DialogTitle><DialogDescription>Demo mode works immediately. Live mode uses the OpenAI API key entered for this session.</DialogDescription><Choice label={tr('运行方式','Run mode')} value={mode} items={options(lang==='zh'?{demo:'演示 · 内置样本与规则',live:'实时调用 · OpenAI'}:{demo:'Demo · built-in samples & rules',live:'Live · OpenAI'})} onChange={v=>{setMode(v as any);reset()}}/><label>OpenAI API key<input type="password" autoComplete="off" value={key} onChange={e=>setKey(e.target.value)} placeholder={tr('仅保存在本页内存，刷新即清除','Stored only in page memory; cleared on refresh')}/></label><label>Model<input value={model} readOnly aria-readonly="true"/></label><p className="helper">Your key is held only in this page’s memory and is cleared on refresh. It is not included in exported run logs.</p><button className="primary" onClick={()=>setSettings(false)}>{tr('保存本次会话设置','Save session settings')}</button></DialogContent></Dialog>
 <Dialog open={!!detail} onOpenChange={v=>!v&&setDetail(null)}><DialogContent className="dialog-wide"><DialogTitle>{tr('运行记录与原始输出','Run log & raw output')}</DialogTitle><DialogDescription>{tr('演示输出和真实模型输出通过 mode 字段区分。','Demo and live-model outputs are distinguished by the mode field.')}</DialogDescription><pre className="log-json">{JSON.stringify(detail,null,2)}</pre><button className="ghost" onClick={()=>saveJSON('claimguard-run-detail.json',detail)}><Download/>{tr('下载此记录','Download this record')}</button></DialogContent></Dialog>
 <Dialog open={showPreview} onOpenChange={setShowPreview}><DialogContent className="dialog-wide"><DialogTitle>{tr('票据原件','Original receipt')}</DialogTitle><DialogDescription>{file?.name}</DialogDescription>{file&&file.mime.startsWith('image/')?<img className="thumb-preview" src={`data:${file.mime};base64,${file.data}`} alt={tr('票据原件','Original receipt')}/>:file?<a className="ghost" href={`data:${file.mime};base64,${file.data}`} download={file.name}>{tr('下载 PDF 原件查看','Download original PDF')}</a>:null}</DialogContent></Dialog>
 </main>
}
