// Pure prototype logic. Demonstration policy evaluation is NOT an AI result.
export type Data = Record<string, any>;
export type Policy = {policy_id:string;category:string;title:string;rule:string;exceptions:string;source:string;effective_date:string;expiry_date:string|null;[key:string]:any};
export type Assessment={status:'passed'|'not_passed'|'likely_eligible'|'likely_ineligible'|'needs_human_review';policy_ids:string[];rationale:string;missing_evidence:string[];uncertainty:string[];next_action:string};
export const CORE=['merchant','date','amount','currency','category'];
export const FIELDS=[...CORE,'tax_amount','receipt_id','payment_method'];
export const LABELS:Record<string,string>={merchant:'Merchant',date:'Receipt date',amount:'Receipt total',currency:'Currency',category:'Expense category',tax_amount:'Tax amount',receipt_id:'Receipt ID',payment_method:'Payment method'};
export const CATEGORY:Record<string,string>={meal:'Meal',transport:'Transport',hotel:'Hotel',airfare:'Airfare',other:'Other',unclear:'Unclear'};
export const STATUS:Record<string,string>={passed:'Passed policy pre-screen',not_passed:'Did not pass policy pre-screen',likely_eligible:'Likely eligible',likely_ineligible:'Likely ineligible',needs_human_review:'Needs human review'};
export function validDate(v:unknown):v is string{return typeof v==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(v)&&!Number.isNaN(Date.parse(v))&&new Date(v).toISOString().slice(0,10)===v}
export function decimal(v:unknown):{n:bigint;d:bigint}|null{if(typeof v!=='number'||!Number.isFinite(v)||v<0)return null;const s=v.toString();if(s.includes('e'))return null;const [a,b='']=s.split('.');return {n:BigInt(a+b),d:BigInt(10)**BigInt(b.length)}}
export function moneyEqual(a:unknown,b:unknown){const x=decimal(a),y=decimal(b);return !!x&&!!y&&x.n*y.d===y.n*x.d}
export function exceeds(amount:unknown,rate:unknown,limit:number,units:unknown){const a=decimal(amount),r=decimal(rate),u=decimal(units);return !!a&&!!r&&!!u&&u.n>BigInt(0)&&a.n*r.n*u.d>BigInt(limit)*u.n*a.d*r.d}
export function schemaErrors(value:any,s:any,path='$'):string[]{const errs:string[]=[];if(s.enum&&!s.enum.includes(value))errs.push(path+': Invalid option');if(s.type){const types=Array.isArray(s.type)?s.type:[s.type];const t=value===null?'null':Array.isArray(value)?'array':typeof value==='object'?'object':typeof value==='number'&&Number.isInteger(value)?'integer':typeof value;if(!types.includes(t)&&!(t==='integer'&&types.includes('number')))return [path+': Invalid type']}
if(value===null)return errs;if(typeof value==='object'&&!Array.isArray(value)){for(const k of s.required||[])if(!(k in value))errs.push(path+'.'+k+': Missing field');for(const k of Object.keys(value)){if(s.properties?.[k])errs.push(...schemaErrors(value[k],s.properties[k],path+'.'+k));else if(s.additionalProperties===false)errs.push(path+'.'+k+': Unexpected field')}}
if(Array.isArray(value)){if(s.uniqueItems&&new Set(value.map(x=>JSON.stringify(x))).size!==value.length)errs.push(path+': Duplicate value');value.forEach((x,i)=>errs.push(...schemaErrors(x,s.items||{},`${path}[${i}]`)))}if(typeof value==='string'){if(s.pattern&&!new RegExp(s.pattern).test(value))errs.push(path+': Invalid format');if(s.format==='date'&&!validDate(value))errs.push(path+': Invalid date')}if(typeof value==='number'&&(!Number.isFinite(value)||(s.minimum!==undefined&&value<s.minimum)||(s.maximum!==undefined&&value>s.maximum)||(s.exclusiveMinimum!==undefined&&value<=s.exclusiveMinimum)))errs.push(path+': Number out of range');return errs}
export function validation(claim:Data,ctx:Data,original:Data=claim):string[]{const e:string[]=[];for(const c of [original,claim]){for(const k of CORE){if(c[k]===null||c[k]===undefined||c[k]===''||c[k]==='unclear')e.push(`${LABELS[k]} is missing or cannot be confirmed`);if(typeof c.field_confidence?.[k]!=='number'||c.field_confidence[k]<.75)e.push(`${LABELS[k]} has low extraction confidence`)}if(c.attack_detected)e.push('Unsafe instruction detected in receipt');if((c.warnings||[]).some((x:string)=>/MULTIPLE_RECEIPTS|refund|credit/i.test(x)))e.push('Multiple receipts or a refund require human review');if(!validDate(c.date))e.push('Receipt date is invalid');if(!decimal(c.amount))e.push('Amount is invalid');if(typeof c.currency!=='string'||!(/^[A-Z]{3}$/).test(c.currency))e.push('Currency is invalid')}
if(ctx.claimed_amount===null||ctx.claimed_amount===undefined)e.push('Enter the claimed amount');else if(!moneyEqual(claim.amount,ctx.claimed_amount))e.push('Claimed amount conflicts with the receipt total');if(!ctx.claimed_currency||claim.currency!==ctx.claimed_currency)e.push('Claim currency conflicts with the receipt currency');if(ctx.expense_category!==claim.category)e.push('Expense category conflicts with the receipt category');if(ctx.expense_date!==claim.date)e.push('Expense date conflicts with the receipt date');if(!validDate(ctx.submitted_date))e.push('Submission date is invalid');if(/ignore all|ignore polic|bypass|approve regardless|忽略政策|直接批准|绕过/i.test(ctx.business_purpose||''))e.push('Unsafe instruction detected in the submitted context');return [...new Set(e)]}
export function intakeValidation(claim:Data,ctx:Data,original:Data=claim):string[]{
 const issues=validation(claim,ctx,original), need=(ok:boolean,label:string)=>{if(!ok)issues.push(`${label} is required`)};
 need(!!ctx.business_purpose?.trim(),'Business purpose');need(ctx.itemized_receipt!==null&&ctx.itemized_receipt!==undefined,'Itemized receipt status');need(ctx.receipt_lost!==null&&ctx.receipt_lost!==undefined,'Receipt status');need(['clear','duplicate_found'].includes(ctx.duplicate_check),'Historical duplicate check');need(['documented','not_obtained'].includes(ctx.manager_approval),'Manager approval status');
 switch(ctx.expense_category){case'hotel':break;case'meal':need(Number.isInteger(ctx.attendee_count)&&ctx.attendee_count>0,'Attendee count');need(ctx.contains_alcohol!==null&&ctx.contains_alcohol!==undefined,'Alcohol confirmation');need(ctx.client_meal!==null&&ctx.client_meal!==undefined,'Client-meal confirmation');if(ctx.client_meal)need(ctx.attendee_details_present===true,'Client attendee details');break;case'transport':need(!!ctx.transport_mode,'Transport mode');need(ctx.route_evidence_present!==null&&ctx.route_evidence_present!==undefined,'Route-evidence confirmation');if(['taxi','ride_hail'].includes(ctx.transport_mode))need(ctx.night_travel!==null&&ctx.night_travel!==undefined,'Night-travel confirmation');break;case'airfare':need(!!ctx.flight_class,'Cabin class');need(['obtained','not_obtained'].includes(ctx.preapproval_status),'Pre-approval status');break;default:need(false,'A supported expense category')}
 if(ctx.claimed_currency&&ctx.claimed_currency!=='SGD'){need(typeof ctx.fx_rate_to_sgd==='number'&&ctx.fx_rate_to_sgd>0,'Documented FX rate');need(ctx.fx_evidence_present===true,'FX evidence')}
 return [...new Set(issues)];
}
export function contextComplete(ctx:Data){return intakeValidation({merchant:'x',date:ctx.expense_date,amount:ctx.claimed_amount,currency:ctx.claimed_currency,category:ctx.expense_category,field_confidence:{merchant:1,date:1,amount:1,currency:1,category:1}},ctx).filter(x=>!/(conflicts with|low extraction confidence|Unsafe instruction)/.test(x)).length===0}
export function retrieve(claim:Data,ctx:Data,cards:Policy[]){const selection_reasons:Record<string,string[]>={},flags:string[]=[];const add=(ids:string[],why:string)=>ids.forEach(id=>(selection_reasons[id]??=[]).push(why));const flag=(s:string)=>{if(!flags.includes(s))flags.push(s)};if(!validDate(claim.date))return {policy_ids:[],policy_cards:[] as Policy[],selection_reasons,flags:['invalid_or_missing_date'],retrieval_status:'needs_human_review'};
add(['DOC-001','GEN-002','GEN-003','GEN-004'],'mandatory_general');switch(claim.category){case'meal':add(['MEAL-001','MEAL-002','MEAL-003'],'meal_rules');break;case'hotel':add(['HOTEL-001','HOTEL-002'],'hotel_rules');if(!Number.isInteger(ctx.hotel_nights)||ctx.hotel_nights<=0||!decimal(claim.amount)||(claim.currency!=='SGD'&&(!decimal(ctx.fx_rate_to_sgd)||ctx.fx_rate_to_sgd<=0||ctx.fx_evidence_present!==true))){add(['HOTEL-003'],'hotel_exception_cannot_be_excluded');flag('hotel_basis_incomplete')}else if(exceeds(claim.amount,claim.currency==='SGD'?1:ctx.fx_rate_to_sgd,250,ctx.hotel_nights))add(['HOTEL-003'],'over_limit_hotel');break;case'airfare':add(['AIR-001','AIR-002'],'flight_rules');break;case'transport':add(['TRANSPORT-004'],'route_required');if(ctx.transport_mode==='public')add(['TRANSPORT-001'],'public_transport');else if(['taxi','ride_hail'].includes(ctx.transport_mode)){add(['TRANSPORT-002'],'taxi_transport');if(ctx.night_travel!==false){add(['TRANSPORT-003'],'night_or_unknown_time');if(ctx.night_travel!==true)flag('night_status_unknown')}}else{add(['TRANSPORT-001','TRANSPORT-002','TRANSPORT-003'],'unknown_mode_requires_all_transport_rules');flag('unsupported_or_unknown_transport_mode')}break;default:flag('unsupported_category')}
if(typeof claim.currency!=='string'||!/^[A-Z]{3}$/.test(claim.currency))flag('currency_unknown_or_invalid');else if(claim.currency!=='SGD')add(['FX-001'],'foreign_currency');if(ctx.receipt_lost!==false||/lost receipt|遗失|丢失/i.test(ctx.business_purpose||''))add(['LOST-001'],'lost_or_unknown_receipt_status');if(claim.attack_detected||/ignore all|ignore polic|bypass|approve regardless|忽略政策|直接批准|绕过/i.test(ctx.business_purpose||''))flag('attack_signal');const active:Record<string,Policy[]>={};for(const p of cards){if(!validDate(p.effective_date)||(p.expiry_date&&!validDate(p.expiry_date))){flag('invalid_policy_date');continue}if(p.effective_date<=claim.date&&(!p.expiry_date||p.expiry_date>=claim.date))(active[p.policy_id]??=[]).push(p)}const selected:Policy[]=[];for(const id of Object.keys(selection_reasons).sort()){const versions=active[id]||[];if(!versions.length)flag('missing_active_policy:'+id);if(versions.length>1)flag('policy_conflict:'+id);selected.push(...versions)}return{policy_ids:[...new Set(selected.map(p=>p.policy_id))].sort(),policy_cards:selected,selection_reasons,flags,retrieval_status:flags.length?'needs_human_review':'ready_for_assessment'}}
export function human(issues:string[]):Assessment{return {status:'needs_human_review',policy_ids:[],rationale:'The claim contains information that needs verification; pre-screening has stopped.',missing_evidence:issues,uncertainty:['After adding or correcting information, Finance should still review the original risks.'],next_action:'Download the human-review packet and submit it with the original receipt to Finance.'}}
export function demoAssess(c:Data,x:Data,r:ReturnType<typeof retrieve>):Assessment{const missing:string[]=[],violations:string[]=[],ids=new Set<string>();const need=(ok:boolean,msg:string,id:string)=>{if(!ok){missing.push(msg);ids.add(id)}};const fail=(yes:boolean,msg:string,id:string)=>{if(yes){violations.push(msg);ids.add(id)}};
need(x.itemized_receipt===true,'Provide a clear itemized receipt','DOC-001');need(!!x.business_purpose?.trim(),'Enter the business purpose','GEN-004');need(x.manager_approval==='documented'&&x.evidence_refs?.length>0,'Provide manager approval evidence','GEN-004');need(x.duplicate_check!=='unknown','Complete the duplicate-claim check','GEN-003');fail(x.duplicate_check==='duplicate','A duplicate claim is confirmed','GEN-003');const days=validDate(x.submitted_date)?(Date.parse(x.submitted_date)-Date.parse(c.date))/86400000:NaN;need(Number.isFinite(days)&&days>=0,'Verify the submission date','GEN-002');fail(days>30,'Submitted more than 30 days after the expense','GEN-002');let rate=1;if(c.currency!=='SGD'){rate=x.fx_rate_to_sgd;need(typeof rate==='number'&&rate>0&&x.fx_evidence_present===true,'Provide exchange-rate and payment evidence','FX-001')}need(x.receipt_lost===false,'A lost receipt requires a declaration and Finance review','LOST-001');
switch(c.category){case'meal':need(Number.isInteger(x.attendee_count)&&x.attendee_count>0,'Provide attendee count','MEAL-001');need(x.contains_alcohol!==null&&x.contains_alcohol!==undefined,'Confirm whether alcohol is included','MEAL-002');need(x.client_meal!==null&&x.client_meal!==undefined,'Confirm whether this is a client meal','MEAL-003');if(x.client_meal)need(x.attendee_details_present===true,'Provide client and attendee details','MEAL-003');fail(x.contains_alcohol===true,'The claim includes non-reimbursable alcohol','MEAL-002');fail(exceeds(c.amount,rate,50,x.attendee_count),'Meal exceeds the SGD 50 per-person limit','MEAL-001');break;case'hotel':need(Number.isInteger(x.hotel_nights)&&x.hotel_nights>0,'Confirm hotel nights','HOTEL-001');need(x.personal_items_present!==null&&x.personal_items_present!==undefined,'Confirm whether personal items are included','HOTEL-002');fail(x.personal_items_present===true,'Hotel claim includes personal items','HOTEL-002');need(!exceeds(c.amount,rate,250,x.hotel_nights),'Exceeds SGD 250 per night; provide pre-approval if available and request an exception review','HOTEL-003');break;case'transport':need(x.route_evidence_present===true,'Provide date, route, and business-purpose evidence','TRANSPORT-004');if(['taxi','ride_hail'].includes(x.transport_mode)){need(typeof x.night_travel==='boolean','Confirm whether travel was for business between 22:00 and 06:00','TRANSPORT-003');fail(exceeds(c.amount,rate,x.night_travel?120:80,1),'Transport expense exceeds the applicable trip limit',x.night_travel?'TRANSPORT-003':'TRANSPORT-002')}else need(x.transport_mode==='public','Confirm transport mode','TRANSPORT-004');if(/commut|通勤/i.test(x.business_purpose||''))need(false,'Business versus personal commuting requires Finance confirmation','TRANSPORT-001');break;case'airfare':need(!!x.flight_class,'Confirm flight cabin class','AIR-001');fail(!!x.flight_class&&x.flight_class!=='economy','Only economy-class airfare is reimbursable','AIR-001');need(x.preapproval_status==='documented'&&x.evidence_refs?.length>0,'Provide pre-approval evidence','AIR-002');break;default:missing.push('Expense category is outside the current policy scope')}
const status=missing.length||r.flags.length?'needs_human_review':violations.length?'likely_ineligible':'likely_eligible';return {status,policy_ids:(ids.size?[...ids]:r.policy_ids).filter(id=>r.policy_ids.includes(id)),rationale:[...violations,...missing].join('; ')||'The available demonstration information meets the teaching-policy rules; Finance still makes the final decision.',missing_evidence:missing,uncertainty:r.flags,next_action:status==='likely_eligible'?'Keep the receipt and approval evidence, then submit to Finance.':status==='likely_ineligible'?'Check the non-compliant items and correct the claim before Finance review if needed.':'Provide the listed materials and submit for Finance review.'}}
export function guidanceFallback(a:Assessment){return `Pre-screening result: ${a.status}. ${a.policy_ids.length?'Policy references: '+a.policy_ids.join(', ')+'. ':''}Submit the claim and supporting evidence to Finance. Finance makes the final decision.`}
export function detectMime(bytes:Uint8Array){if(bytes.length>=8&&[137,80,78,71,13,10,26,10].every((b,i)=>bytes[i]===b))return'image/png';if(bytes[0]===255&&bytes[1]===216&&bytes[2]===255)return'image/jpeg';if(new TextDecoder().decode(bytes.slice(0,5))==='%PDF-')return'application/pdf';return null}
export function auditCorrections(original:Data,current:Data){return FIELDS.filter(k=>original[k]!==current[k]).map(field=>({field,old_value:original[field],new_value:current[field],actor:'employee',timestamp:new Date().toISOString(),evidence_ref:'employee-correction-unverified'}))}
export function validateCitations(a:Assessment,ids:string[]){return new Set(a.policy_ids).size===a.policy_ids.length&&a.policy_ids.every(id=>ids.includes(id))}
