// Pure prototype logic. Demonstration policy evaluation is NOT an AI result.
export type Data = Record<string, any>;
export type Policy = {policy_id:string;category:string;title:string;rule:string;exceptions:string;source:string;effective_date:string;expiry_date:string|null;[key:string]:any};
export type Assessment={status:'likely_eligible'|'likely_ineligible'|'needs_human_review';policy_ids:string[];rationale:string;missing_evidence:string[];uncertainty:string[];next_action:string};
export const CORE=['merchant','date','amount','currency','category'];
export const FIELDS=[...CORE,'tax_amount','receipt_id','payment_method'];
export const LABELS:Record<string,string>={merchant:'商户',date:'票据日期',amount:'票据总额',currency:'币种',category:'费用类别',tax_amount:'税额',receipt_id:'票据编号',payment_method:'付款方式'};
export const CATEGORY:Record<string,string>={meal:'餐饮',transport:'交通',hotel:'住宿',airfare:'差旅 / 航班',other:'其他',unclear:'无法确定'};
export const STATUS:Record<string,string>={likely_eligible:'可能符合要求',likely_ineligible:'可能不符合要求',needs_human_review:'需要人工审核'};
export function validDate(v:unknown):v is string{return typeof v==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(v)&&!Number.isNaN(Date.parse(v))&&new Date(v).toISOString().slice(0,10)===v}
export function decimal(v:unknown):{n:bigint;d:bigint}|null{if(typeof v!=='number'||!Number.isFinite(v)||v<0)return null;const s=v.toString();if(s.includes('e'))return null;const [a,b='']=s.split('.');return {n:BigInt(a+b),d:BigInt(10)**BigInt(b.length)}}
export function moneyEqual(a:unknown,b:unknown){const x=decimal(a),y=decimal(b);return !!x&&!!y&&x.n*y.d===y.n*x.d}
export function exceeds(amount:unknown,rate:unknown,limit:number,units:unknown){const a=decimal(amount),r=decimal(rate),u=decimal(units);return !!a&&!!r&&!!u&&u.n>BigInt(0)&&a.n*r.n*u.d>BigInt(limit)*u.n*a.d*r.d}
export function schemaErrors(value:any,s:any,path='$'):string[]{const errs:string[]=[];if(s.enum&&!s.enum.includes(value))errs.push(path+': 无效选项');if(s.type){const types=Array.isArray(s.type)?s.type:[s.type];const t=value===null?'null':Array.isArray(value)?'array':typeof value==='object'?'object':typeof value==='number'&&Number.isInteger(value)?'integer':typeof value;if(!types.includes(t)&&!(t==='integer'&&types.includes('number')))return [path+': 类型错误']}
if(value===null)return errs;if(typeof value==='object'&&!Array.isArray(value)){for(const k of s.required||[])if(!(k in value))errs.push(path+'.'+k+': 缺少字段');for(const k of Object.keys(value)){if(s.properties?.[k])errs.push(...schemaErrors(value[k],s.properties[k],path+'.'+k));else if(s.additionalProperties===false)errs.push(path+'.'+k+': 未声明字段')}}
if(Array.isArray(value)){if(s.uniqueItems&&new Set(value.map(x=>JSON.stringify(x))).size!==value.length)errs.push(path+': 重复值');value.forEach((x,i)=>errs.push(...schemaErrors(x,s.items||{},`${path}[${i}]`)))}if(typeof value==='string'){if(s.pattern&&!new RegExp(s.pattern).test(value))errs.push(path+': 格式错误');if(s.format==='date'&&!validDate(value))errs.push(path+': 日期无效')}if(typeof value==='number'&&(!Number.isFinite(value)||(s.minimum!==undefined&&value<s.minimum)||(s.maximum!==undefined&&value>s.maximum)||(s.exclusiveMinimum!==undefined&&value<=s.exclusiveMinimum)))errs.push(path+': 数值超出范围');return errs}
export function validation(claim:Data,ctx:Data,original:Data=claim):string[]{const e:string[]=[];for(const c of [original,claim]){for(const k of CORE){if(c[k]===null||c[k]===undefined||c[k]===''||c[k]==='unclear')e.push(`${LABELS[k]}缺失或无法确认`);if(typeof c.field_confidence?.[k]!=='number'||c.field_confidence[k]<.75)e.push(`${LABELS[k]}原始置信度不足`)}if(c.attack_detected)e.push('检测到票据内越权指令');if((c.warnings||[]).some((x:string)=>/MULTIPLE_RECEIPTS|refund|credit/i.test(x)))e.push('多张票据或退款需要人工核对');if(!validDate(c.date))e.push('票据日期无效');if(!decimal(c.amount))e.push('金额无效');if(typeof c.currency!=='string'||!(/^[A-Z]{3}$/).test(c.currency))e.push('币种无效')}
if(ctx.claimed_amount===null||ctx.claimed_amount===undefined)e.push('请填写申报金额');else if(!moneyEqual(claim.amount,ctx.claimed_amount))e.push('申报金额与票据总额冲突');if(!ctx.claimed_currency||claim.currency!==ctx.claimed_currency)e.push('申报币种与票据币种冲突');if(ctx.expense_category!==claim.category)e.push('员工类别与票据类别冲突');if(ctx.expense_date!==claim.date)e.push('员工日期与票据日期冲突');if(!validDate(ctx.submitted_date))e.push('提交日期无效');if(/ignore all|ignore polic|bypass|approve regardless|忽略政策|直接批准|绕过/i.test(ctx.business_purpose||''))e.push('检测到用户越权指令');return [...new Set(e)]}
export function retrieve(claim:Data,ctx:Data,cards:Policy[]){const selection_reasons:Record<string,string[]>={},flags:string[]=[];const add=(ids:string[],why:string)=>ids.forEach(id=>(selection_reasons[id]??=[]).push(why));const flag=(s:string)=>{if(!flags.includes(s))flags.push(s)};if(!validDate(claim.date))return {policy_ids:[],policy_cards:[] as Policy[],selection_reasons,flags:['invalid_or_missing_date'],retrieval_status:'needs_human_review'};
add(['DOC-001','GEN-002','GEN-003','GEN-004'],'mandatory_general');switch(claim.category){case'meal':add(['MEAL-001','MEAL-002','MEAL-003'],'meal_rules');break;case'hotel':add(['HOTEL-001','HOTEL-002'],'hotel_rules');if(!Number.isInteger(ctx.hotel_nights)||ctx.hotel_nights<=0||!decimal(claim.amount)||(claim.currency!=='SGD'&&(!decimal(ctx.fx_rate_to_sgd)||ctx.fx_rate_to_sgd<=0||ctx.fx_evidence_present!==true))){add(['HOTEL-003'],'hotel_exception_cannot_be_excluded');flag('hotel_basis_incomplete')}else if(exceeds(claim.amount,claim.currency==='SGD'?1:ctx.fx_rate_to_sgd,250,ctx.hotel_nights))add(['HOTEL-003'],'over_limit_hotel');break;case'airfare':add(['AIR-001','AIR-002'],'flight_rules');break;case'transport':add(['TRANSPORT-004'],'route_required');if(ctx.transport_mode==='public')add(['TRANSPORT-001'],'public_transport');else if(['taxi','ride_hail'].includes(ctx.transport_mode)){add(['TRANSPORT-002'],'taxi_transport');if(ctx.night_travel!==false){add(['TRANSPORT-003'],'night_or_unknown_time');if(ctx.night_travel!==true)flag('night_status_unknown')}}else{add(['TRANSPORT-001','TRANSPORT-002','TRANSPORT-003'],'unknown_mode_requires_all_transport_rules');flag('unsupported_or_unknown_transport_mode')}break;default:flag('unsupported_category')}
if(typeof claim.currency!=='string'||!/^[A-Z]{3}$/.test(claim.currency))flag('currency_unknown_or_invalid');else if(claim.currency!=='SGD')add(['FX-001'],'foreign_currency');if(ctx.receipt_lost!==false||/lost receipt|遗失|丢失/i.test(ctx.business_purpose||''))add(['LOST-001'],'lost_or_unknown_receipt_status');if(claim.attack_detected||/ignore all|ignore polic|bypass|approve regardless|忽略政策|直接批准|绕过/i.test(ctx.business_purpose||''))flag('attack_signal');const active:Record<string,Policy[]>={};for(const p of cards){if(!validDate(p.effective_date)||(p.expiry_date&&!validDate(p.expiry_date))){flag('invalid_policy_date');continue}if(p.effective_date<=claim.date&&(!p.expiry_date||p.expiry_date>=claim.date))(active[p.policy_id]??=[]).push(p)}const selected:Policy[]=[];for(const id of Object.keys(selection_reasons).sort()){const versions=active[id]||[];if(!versions.length)flag('missing_active_policy:'+id);if(versions.length>1)flag('policy_conflict:'+id);selected.push(...versions)}return{policy_ids:[...new Set(selected.map(p=>p.policy_id))].sort(),policy_cards:selected,selection_reasons,flags,retrieval_status:flags.length?'needs_human_review':'ready_for_assessment'}}
export function human(issues:string[]):Assessment{return {status:'needs_human_review',policy_ids:[],rationale:'申请包含需要核对的信息，自动预审已停止。',missing_evidence:issues,uncertainty:['补充或更正信息后，仍需财务人员复核原始风险。'],next_action:'下载人工审核材料，连同原始票据提交给财务。'}}
export function demoAssess(c:Data,x:Data,r:ReturnType<typeof retrieve>):Assessment{const missing:string[]=[],violations:string[]=[],ids=new Set<string>();const need=(ok:boolean,msg:string,id:string)=>{if(!ok){missing.push(msg);ids.add(id)}};const fail=(yes:boolean,msg:string,id:string)=>{if(yes){violations.push(msg);ids.add(id)}};
need(x.itemized_receipt===true,'提供清晰的明细票据','DOC-001');need(!!x.business_purpose?.trim(),'填写业务用途','GEN-004');need(x.manager_approval==='documented'&&x.evidence_refs?.length>0,'提供经理审批记录','GEN-004');need(x.duplicate_check!=='unknown','完成历史报销重复核查','GEN-003');fail(x.duplicate_check==='duplicate','已确认属于重复报销','GEN-003');const days=validDate(x.submitted_date)?(Date.parse(x.submitted_date)-Date.parse(c.date))/86400000:NaN;need(Number.isFinite(days)&&days>=0,'核对提交日期','GEN-002');fail(days>30,'超过30天提交期限','GEN-002');let rate=1;if(c.currency!=='SGD'){rate=x.fx_rate_to_sgd;need(typeof rate==='number'&&rate>0&&x.fx_evidence_present===true,'提供汇率与付款证明','FX-001')}need(x.receipt_lost===false,'遗失票据需声明及财务复核','LOST-001');
switch(c.category){case'meal':need(Number.isInteger(x.attendee_count)&&x.attendee_count>0,'提供用餐人数','MEAL-001');need(x.contains_alcohol!==null&&x.contains_alcohol!==undefined,'确认是否含酒精','MEAL-002');need(x.client_meal!==null&&x.client_meal!==undefined,'确认是否为客户餐饮','MEAL-003');if(x.client_meal)need(x.attendee_details_present===true,'提供客户与出席人资料','MEAL-003');fail(x.contains_alcohol===true,'申报包含不可报销的酒精','MEAL-002');fail(exceeds(c.amount,rate,50,x.attendee_count),'餐饮超过每人50 SGD限额','MEAL-001');break;case'hotel':need(Number.isInteger(x.hotel_nights)&&x.hotel_nights>0,'确认住宿晚数','HOTEL-001');need(x.personal_items_present!==null&&x.personal_items_present!==undefined,'确认是否包含个人消费','HOTEL-002');fail(x.personal_items_present===true,'住宿申报包含个人消费','HOTEL-002');need(!exceeds(c.amount,rate,250,x.hotel_nights),'超出250 SGD/晚；附预批记录（如有）并申请财务例外复核','HOTEL-003');break;case'transport':need(x.route_evidence_present===true,'提供日期、起终点与用途证明','TRANSPORT-004');if(['taxi','ride_hail'].includes(x.transport_mode)){need(typeof x.night_travel==='boolean','确认是否为22:00–06:00业务出行','TRANSPORT-003');fail(exceeds(c.amount,rate,x.night_travel?120:80,1),'交通费超过适用单程限额',x.night_travel?'TRANSPORT-003':'TRANSPORT-002')}else need(x.transport_mode==='public','确认交通方式','TRANSPORT-004');if(/commut|通勤/i.test(x.business_purpose||''))need(false,'业务/个人通勤用途需财务确认','TRANSPORT-001');break;case'airfare':need(!!x.flight_class,'确认航班舱位','AIR-001');fail(!!x.flight_class&&x.flight_class!=='economy','仅支持经济舱报销','AIR-001');need(x.preapproval_status==='documented'&&x.evidence_refs?.length>0,'提供出行前审批证明','AIR-002');break;default:missing.push('费用类别不在当前政策范围')}
const status=missing.length||r.flags.length?'needs_human_review':violations.length?'likely_ineligible':'likely_eligible';return {status,policy_ids:(ids.size?[...ids]:r.policy_ids).filter(id=>r.policy_ids.includes(id)),rationale:[...violations,...missing].join('；')||'现有演示信息满足适用教学规则，仍需财务正式审核。',missing_evidence:missing,uncertainty:r.flags,next_action:status==='likely_eligible'?'保留票据及审批证据，提交财务正式审核。':status==='likely_ineligible'?'核对不符合的项目，必要时更正申请后交财务复核。':'补充所列材料，提交财务人工复核。'}}
export function guidanceFallback(a:Assessment){return `Pre-screening result: ${a.status}. ${a.policy_ids.length?'Policy references: '+a.policy_ids.join(', ')+'. ':''}Submit the claim and supporting evidence to Finance. Finance makes the final decision.`}
export function detectMime(bytes:Uint8Array){if(bytes.length>=8&&[137,80,78,71,13,10,26,10].every((b,i)=>bytes[i]===b))return'image/png';if(bytes[0]===255&&bytes[1]===216&&bytes[2]===255)return'image/jpeg';if(new TextDecoder().decode(bytes.slice(0,5))==='%PDF-')return'application/pdf';return null}
export function auditCorrections(original:Data,current:Data){return FIELDS.filter(k=>original[k]!==current[k]).map(field=>({field,old_value:original[field],new_value:current[field],actor:'employee',timestamp:new Date().toISOString(),evidence_ref:'employee-correction-unverified'}))}
export function validateCitations(a:Assessment,ids:string[]){return a.policy_ids.every(id=>ids.includes(id))}
